server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mlMutante
    username: sa
    password: 
  jpa:
    database: H2
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  application:
    name: mlMutantes

  